#!/bin/bash


export VM_HAS_REQUIRED_LIBS="false"

export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="false"

export VM_HAS_CGAL="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="false"


export VM_BOOST_PATH=""

export VM_QT_PATH=""

export VM_PYTHON_PATH=""

export VM_BULLET_PATH=""