#!/bin/bash

export VM_HAS_REQUIRED_LIBS="true"

export VM_MAKE_OPTIONS="-j4"

export VM_MAX_PARALLEL_TESTS="4"

export VM_CCACHE_MAXSIZE="16G"


export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true"

export VM_HAS_CGAL="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="false"


export VM_QT_PATH="/opt/homebrew/opt/qt5"

export VM_PYTHON_EXECUTABLE=""
export VM_PYTHON_PYTHONPATH=""
export VM_PYTHON3_EXECUTABLE="/opt/homebrew/bin/python3.8"
export VM_PYTHON3_PYTHONPATH="/opt/homebrew/lib/python3.8/site-packages"
export VM_PYBIND11_CONFIG_EXECUTABLE="pybind11-config-3.8"

if [[ "$CI_PYTHON3_VERSION" == "3.7" ]] && [[ -e "/opt/homebrew/bin/python3.7" ]]; then
    export VM_PYTHON3_EXECUTABLE="/opt/homebrew/bin/python3.7"
    export VM_PYTHON3_PYTHONPATH="/opt/homebrew/lib/python3.7/site-packages"
    export VM_PYBIND11_CONFIG_EXECUTABLE="pybind11-config-3.7"
elif [[ "$CI_PYTHON3_VERSION" == "3.8" ]] && [[ -e "/opt/homebrew/bin/python3.8" ]]; then
    export VM_PYTHON3_EXECUTABLE="/opt/homebrew/bin/python3.8"
    export VM_PYTHON3_PYTHONPATH="/opt/homebrew/lib/python3.8/site-packages"
    export VM_PYBIND11_CONFIG_EXECUTABLE="pybind11-config-3.8"
elif [[ "$CI_PYTHON3_VERSION" == "3.9" ]] && [[ -e "/opt/homebrew/bin/python3.9" ]]; then
    export VM_PYTHON3_EXECUTABLE="/opt/homebrew/bin/python3.9"
    export VM_PYTHON3_PYTHONPATH="/opt/homebrew/lib/python3.9/site-packages"
    export VM_PYBIND11_CONFIG_EXECUTABLE="pybind11-config-3.9"
fi

export PATH="\
/opt/homebrew/opt/gnu-sed/libexec/gnubin:\
/opt/homebrew/opt/coreutils/libexec/gnubin:\
/opt/homebrew/opt/ccache/libexec:\
/opt/homebrew/bin:/opt/homebrew/lib:\
/opt/homebrew/opt/qt5/bin:\
$PATH"
