#!/bin/bash

export VM_HAS_REQUIRED_LIBS="true"

export VM_MAKE_OPTIONS="-j4"

export VM_MAX_PARALLEL_TESTS="4"

export VM_CCACHE_MAXSIZE="16G"


export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true"

export VM_HAS_CGAL="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="false"


export VM_QT_PATH="/opt/homebrew/opt/qt5"

export VM_PYTHON_EXECUTABLE=""
export VM_PYTHON_PYTHONPATH=""
export VM_PYTHON3_EXECUTABLE="/opt/homebrew/bin/python3.8"
export VM_PYTHON3_PYTHONPATH="/opt/homebrew/lib/python3.8/site-packages"
export VM_PYBIND11_CONFIG_EXECUTABLE="$VM_PYTHON3_EXECUTABLE -m pybind11"

export PATH="\
/opt/homebrew/opt/gnu-sed/libexec/gnubin:\
/opt/homebrew/opt/coreutils/libexec/gnubin:\
/opt/homebrew/opt/ccache/libexec:\
/opt/homebrew/bin:/opt/homebrew/lib:\
/opt/homebrew/opt/qt5/bin:\
$PATH"
