#!/bin/bash

export VM_HAS_REQUIRED_LIBS="true"

export VM_MAKE_OPTIONS="-j4"

export VM_MAX_PARALLEL_TESTS="4"

export VM_CCACHE_MAXSIZE="16G"


export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true"

export VM_HAS_CGAL="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="false"


export VM_QT_PATH="/Users/ci/Qt/5.12.6"

export VM_PYTHON_EXECUTABLE=""
export VM_PYTHON_PYTHONPATH=""
export VM_PYTHON3_EXECUTABLE="/usr/local/opt/python@3.10/bin/python3"
export VM_PYTHON3_PYTHONPATH="/usr/local/lib/python3.10/site-packages"
if [[ -n "$CI_PYTHON3_VERSION" ]] &&
   [[ -e "/usr/local/opt/python@$CI_PYTHON3_VERSION/bin/python3" ]] &&
   [[ -e "/usr/local/lib/python$CI_PYTHON3_VERSION/site-packages" ]]; then
    export VM_PYTHON3_EXECUTABLE="/usr/local/opt/python@$CI_PYTHON3_VERSION/bin/python3"
    export VM_PYTHON3_PYTHONPATH="/usr/local/lib/python$CI_PYTHON3_VERSION/site-packages"
fi
export VM_PYBIND11_CONFIG_EXECUTABLE="$VM_PYTHON3_EXECUTABLE -m pybind11"

export PATH="\
/usr/local/opt/gnu-sed/libexec/gnubin:\
/usr/local/opt/coreutils/libexec/gnubin:\
/usr/local/opt/ccache/libexec:\
/usr/local/bin:/usr/local/lib:\
$PATH"
