#!/bin/bash

export VM_HAS_REQUIRED_LIBS="true"

export VM_MAKE_OPTIONS="-j4"

export VM_MAX_PARALLEL_TESTS="4"

export VM_CCACHE_MAXSIZE="16G"


export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true"

export VM_HAS_CGAL="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="false"


export VM_QT_PATH="/Users/ci/Qt/5.12.6"

export VM_PYTHON_EXECUTABLE=""
export VM_PYTHON_PYTHONPATH=""
export VM_PYTHON3_EXECUTABLE="/usr/local/bin/python3.8"
export VM_PYTHON3_PYTHONPATH="/usr/local/lib/python3.8/site-packages"
export VM_PYBIND11_CONFIG_EXECUTABLE="pybind11-config-3.8"

export PATH="\
/usr/local/opt/gnu-sed/libexec/gnubin:\
/usr/local/opt/coreutils/libexec/gnubin:\
/usr/local/opt/ccache/libexec:\
/usr/local/bin:/usr/local/lib:\
$PATH"
