#!/bin/bash

########
# LIBS #
########

# Required libs:
#   Make: sudo yum install cmake3 ninja-build clang ccache
#   Qt: sudo yum install qt5-qtbase
#   Boost: must be compiled
#   Python: sudo yum install python numpy scipy
#   Other: sudo yum install libpng zlib-devel libglew freeglut-devel curl
export VM_HAS_REQUIRED_LIBS="true"

export VM_HAS_BULLET="false" # sudo yum install bullet-devel

export VM_HAS_ASSIMP="false" # sudo yum install assimp-devel

export VM_HAS_CGAL="false" # must be compiled

export VM_HAS_CUDA="false" # http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#redhat-installation

export VM_HAS_OPENCASCADE="false" # must be compiled


#########
# PATHS #
#########

# Empty path means it should be found in $PATH

export VM_BOOST_PATH=""

export VM_QT_PATH=""

export VM_PYTHON_PATH=""

export VM_BULLET_PATH=""