#!/bin/bash

########
# LIBS #
########

# System libs:
#   Make: brew install cmake ninja ccache
#   Qt: must be compiled
#   Boost: brew install boost
#   Python: -
#   Other: brew install glew libpng metis curl
export VM_HAS_REQUIRED_LIBS="false"

export VM_HAS_BULLET="false" # brew install bullet

export VM_HAS_ASSIMP="false" # brew install assimp

export VM_HAS_CGAL="false" # brew install cgal

export VM_HAS_CUDA="false" # http://docs.nvidia.com/cuda/cuda-installation-guide-mac-os-x/index.html

export VM_HAS_OPENCASCADE="false" # brew install homebrew/science/opencascade


#########
# PATHS #
#########

# Empty path means it should be found in $PATH

export VM_BOOST_PATH=""

export VM_QT_PATH=""

export VM_PYTHON_PATH=""

export VM_BULLET_PATH=""