#!/bin/bash

export VM_MAKE_OPTIONS="-j2"


export VM_BOOST_PATH="C:/dev/boost/boost_1_59_0"

export VM_QT_PATH="C:/dev/Qt/5.7"

export VM_PYTHON_PATH="C:/dev/Python/2.7"

export VM_BULLET_PATH=""

export VM_CLCACHE_PATH="C:/dev/clcache"


export VM_HAS_ASSIMP="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="false"