#!/bin/bash

########
# LIBS #
########

# Required libs:
#   Make: sudo apt install cmake ninja-build clang ccache
#   Qt: sudo apt install qt5-default qttools5-dev-tools libqt5opengl5-dev
#   Boost: sudo apt install libboost-atomic-dev libboost-chrono-dev libboost-date-time-dev libboost-filesystem-dev libboost-locale-dev libboost-regex-dev libboost-system-dev libboost-thread-dev
#   Python: sudo apt install python2.7-dev python-numpy python-scipy
#   Other: sudo apt install libpng-dev zlib1g-dev libglew-dev freeglut3-dev
export VM_HAS_REQUIRED_LIBS="true"

export VM_HAS_BULLET="false" # sudo apt install libbullet-dev

export VM_HAS_ASSIMP="false" # sudo apt install libassimp-dev

export VM_HAS_CGAL="false" # sudo apt install libcgal-dev libcgal-qt5-dev

export VM_HAS_CUDA="false" # sudo apt install nvidia-cuda-toolkit

export VM_HAS_OPENCASCADE="false" # sudo apt install liboce-ocaf-dev


#########
# PATHS #
#########

# Empty path means it should be found in $PATH

export VM_BOOST_PATH=""

export VM_QT_PATH=""

export VM_PYTHON_PATH=""

export VM_BULLET_PATH=""