#!/bin/bash

export VM_MAKE_OPTIONS="-j2"


export VM_BOOST_PATH=""

export VM_QT_PATH=""

export VM_PYTHON_PATH=""

export VM_BULLET_PATH=""


export VM_HAS_ASSIMP="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="false"