#!/bin/bash


export VM_HAS_REQUIRED_LIBS="true"

export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true"

export VM_HAS_CGAL="true"

export VM_HAS_CUDA="true"

export VM_HAS_OPENCASCADE="false"


export VM_MAKE_OPTIONS="-j8"

export VM_CUDA_ARCH="sm_50"

export VM_CUDA_NVCC_FLAGS='"-ccbin gcc-6"'
export CUDAHOSTCXX="gcc-6"

# Load Qt environment
source /opt/qt512/bin/qt512-env.sh || true
export QTIFWDIR="/home/sofa/Qt/Tools/QtInstallerFramework/3.0"

