#!/bin/bash


export VM_HAS_REQUIRED_LIBS="true"

export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true"

export VM_HAS_CGAL="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="true"

export VM_MAX_PARALLEL_TESTS="2"

export PATH="/usr/local/opt/ccache/libexec:$PATH"
