#!/bin/bash


export VM_HAS_REQUIRED_LIBS="true"

if [ ! -f /.dockerenv ]; then # not in Docker
    export VM_HAS_BULLET="false"

    export VM_HAS_ASSIMP="true"

    export VM_HAS_CGAL="true"

    export VM_HAS_CUDA="true"

    export VM_HAS_OPENCASCADE="false"


    export VM_MAKE_OPTIONS="-j8"

    export VM_CUDA_ARCH="sm_50"

    export VM_CUDA_HOST_COMPILER="/usr/bin/gcc-6"
fi

export VM_MAX_PARALLEL_TESTS="8" # warning: 2 executors
