#!/bin/bash


export VM_HAS_REQUIRED_LIBS="true"

export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true"

export VM_HAS_CGAL="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="true"


export VM_MAKE_OPTIONS="-j6"

export VM_MAX_PARALLEL_TESTS="6"

export PATH="\
/usr/local/opt/gnu-sed/libexec/gnubin:\
/usr/local/opt/coreutils/libexec/gnubin:\
/usr/local/opt/ccache/libexec:\
/usr/local/opt/qt/bin:\
/usr/local/bin:/usr/local/lib:\
$PATH"
