#!/bin/bash


export VM_HAS_REQUIRED_LIBS="true"

export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true"

export VM_HAS_CGAL="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="false"

export PATH="/lib:/lib64:/bin:$PATH"
export LD_LIBRARY_PATH="/lib:/lib64:/bin:$LD_LIBRARY_PATH"
