#!/bin/bash


export VM_HAS_REQUIRED_LIBS="true"

export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true" # Windows dll included in SOFA

export VM_HAS_CGAL="false"

export VM_HAS_CUDA="true"

export VM_HAS_OPENCASCADE="false"


export VM_BOOST_PATH="C:/boost"

export VM_QT_PATH="C:/Qt/5.12.6"

export VM_PYTHON_PATH="C:/Python27"

export VM_BULLET_PATH=""

# export VM_ASSIMP_PATH="C:/dev/Assimp/4.1.0"


export VM_MAKE_OPTIONS="-j4"
