#!/bin/bash

# Display Name	sofa-ci-dev-ubuntu2004-1
# Name	sofa-ci-dev-ubuntu2004-1
# State	Running
# Template	sed-paris-ubuntu-20.04-lts
# Dynamically Scalable	No
# OS Type	Other Ubuntu (64-bit)
# Attached ISO
# Compute offering	Custom
# # of CPU Cores	7
# CPU (in MHz)	2000
# Memory (in MB)	10240

export VM_HAS_REQUIRED_LIBS="true"

export VM_MAKE_OPTIONS="-j7"

export VM_MAX_PARALLEL_TESTS="7"

if [ ! -f /.dockerenv ]; then # not in Docker
    export VM_HAS_BULLET="false"

    export VM_HAS_ASSIMP="true"

    export VM_HAS_CGAL="true"

    export VM_HAS_CUDA="true"

    export VM_HAS_OPENCASCADE="false"

    export VM_CUDA_ARCH="sm_50"

    export VM_CUDA_HOST_COMPILER="/usr/bin/gcc-6"

    # Load Qt environment
    if [ -e "/opt/qt512/bin/qt512-env.sh" ]; then
        source /opt/qt512/bin/qt512-env.sh || true
    fi
fi
