#!/bin/bash


export VM_HAS_REQUIRED_LIBS="true"

export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true"

export VM_HAS_CGAL="false"

export VM_HAS_CUDA="false"

export VM_HAS_OPENCASCADE="false"

export PATH="/lib:/lib64:/bin:$PATH"
export LD_LIBRARY_PATH="/lib:/lib64:/bin:$LD_LIBRARY_PATH"

echo "DEBUG PATH = $PATH"
echo "DEBUG Clang version:"
clang --version
echo "source /opt/rh/devtoolset-7/enable"
source /opt/rh/devtoolset-7/enable
echo "source /opt/rh/llvm-toolset-7/enable"
source /opt/rh/llvm-toolset-7/enable
echo "DEBUG PATH = $PATH"
echo "DEBUG Clang version:"
clang --version
