#!/bin/bash

export VM_HAS_REQUIRED_LIBS="true"

export VM_HAS_BULLET="false"

export VM_HAS_ASSIMP="true"

export VM_HAS_CGAL="true"

export VM_HAS_CUDA="true"

export VM_HAS_OPENCASCADE="false"


export VM_MAKE_OPTIONS="-j6"

# Load Qt environment
# SAVED_OPTIONS=$(set +o)
# set +o errexit # DISABLE "exit on error"
# source /opt/qt512/bin/qt512-env.sh
# eval "$SAVED_OPTIONS"
