#!/bin/bash


export VM_HAS_REQUIRED_LIBS="true"

if [ ! -f /.dockerenv ]; then # not in Docker
    export VM_HAS_BULLET="false"

    export VM_HAS_ASSIMP="true"

    export VM_HAS_CGAL="false"

    export VM_HAS_CUDA="false"

    export VM_HAS_OPENCASCADE="false"

    export PATH="/lib:/lib64:/bin:$PATH"
    export LD_LIBRARY_PATH="/lib:/lib64:/bin:$LD_LIBRARY_PATH"

    source /opt/rh/devtoolset-7/enable || true
    source /opt/rh/llvm-toolset-7/enable || true
fi

export VM_MAX_PARALLEL_TESTS="4"

# TEMPORARY: prioritize python2
source /opt/rh/python27/enable || true

export PYTHONIOENCODING="UTF-8"
export PYTHONUSERBASE="/tmp/pythonuserbase"
mkdir -p "$PYTHONUSERBASE" && chmod -R 777 "$PYTHONUSERBASE"
export VM_PYTHON_EXECUTABLE="/opt/rh/python27/root/usr/bin/python2.7"
export VM_PYTHON3_EXECUTABLE="/opt/rh/rh-python38/root/usr/bin/python3.8"
