[project]
name = "SOFA-test-suite"
version = "0.1.0"
description = "Test suite base don python script for Unit, Scene and Regression tests"
requires-python = ">=3.10"
dependencies = []

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project.scripts]
sofa-scene-tests = "sofa_scene_tests.__main__:main"
sofa-unit-tests = "sofa_unit_tests.__main__:main"

[tool.setuptools]
packages = ["sofa_scene_tests","sofa_unit_tests"]
